pipeline {
    agent any 
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f AirTNT/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now Archiving the artifacts.....'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment') {
            steps {
                build job: 'Deploy_Application_Staging_Env'
            }
        }
    }
}